import type { Metadata } from "next";
import { Inter } from "next/font/google";

export const metadata: Metadata = {
  title: "BookShelf",
  description: "Generated by BookShelf",
};

export default function AdminLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="bg-[url('/assets/images/bg2.png')] h-screen bg-cover">
      <div className="flex w-full h-screen justify-center items-center">
        {children}
      </div>
    </div>
  );
}
