import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-[url('/assets/images/bg2.png')] h-screen bg-cover">
          <div className="flex w-full h-full justify-center items-center">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
